services:
    db_app:
        image: postgres:16.4
        container_name: db_app
        environment:
            POSTGRES_USER: local
            POSTGRES_PASSWORD: local
            POSTGRES_DB: account_management_local
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"